[package]
name = "scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
rand.workspace = true
sqlx.workspace = true
itertools = "0.14.0"
rayon = "1.10.0"
num-format = "0.4.4"

[dev-dependencies]
approx = "0.5.1"

[[bin]]
name = "scheduler-eval"
path = "src/bin/scheduler_eval.rs"